### ISSUE TITLE
希望可以自定义 EServer 目录内容

### ISSUE THREAD

**Issue by nkeweb** [xianyunleo/EServer#101]
<img width="638" alt="image" src="https://github.com/xianyunleo/EServer/assets/154671524/72db635d-9f36-47e3-8ab7-63ea814852ff">
<img width="900" alt="image" src="https://github.com/xianyunleo/EServer/assets/154671524/0fa4cfbc-5a6d-40ff-8ed2-cf1d1bee8184">
希望这个这个EServer目录的东西可以在第一次进去的时候自定义,对于强迫症来说有点难受,对于软件安装的notepad-- 我更喜欢放在应用目录,但是数据库的储存信息我喜欢放文稿目录,网站代码喜欢放用户目录

**Comment by xianyunleo** [comment]
有需要可下载源码，自行修改。
