### ISSUE TITLE
Mac电脑M芯片支持问题

### ISSUE THREAD

**Issue by dongshan1986** [xianyunleo/EServer#102]
这玩意很好用，是MAC下PHP环境搭建的最好工具，没有之一，以前Intel内核下使用很爽:
1. 本人M2 PRO芯片的Mac，系统MacOS 14.2.1
2. 从官网或者GitHub下载的dmg，打开后无法打开，直接提示移除到回收站。问题，为什么会无法打开，若需要M内核的电脑我可以协助
3. 从GitHub下载源码编译有错误，但是可以编译成功App。问题，是否有办法解决这个错误?
![error](https://github.com/xianyunleo/EServer/assets/6813286/e5983b73-989b-4064-af9d-2fbbf760e5b0)
4. 自己编译成功的App打开后，提示安装Rosetta。问题: Electron开发，应该可以脱离Rosetta，苹果也后续也不可能生产支持Intel内核电脑，这玩意完全没必要安装，若需要协助修改代码，我也可以的，建议完美支持M内核，是趋势
![rosetta](https://github.com/xianyunleo/EServer/assets/6813286/b2a3ada9-5702-4a0f-8c3f-27c4ffbea6eb)

**Comment by xianyunleo** [comment]
2看文档
3不用管，或者给Library下的所有bin批量赋值可执行权限
4.https://github.com/xianyunleo/EServer/issues/97
