### ISSUE TITLE
一点建议（自定义服务和软件）

### ISSUE THREAD

**Issue by zhaoyuzhi983** [xianyunleo/EServer#104]
作者可以参考https://github.com/redis-windows/redis-windows，比较新版的redis，另外为什么nginx不提供版本切换呢？还有希望可以让用户自行添加组件的版本，这样更为灵活。最后感谢作者无私的作品！

**Comment by xianyunleo** [comment]
自定义服务和软件，参考文档 https://www.kancloud.cn/liu1040063186/easysrv/3148342
