### ISSUE TITLE
php 的gd，不支持webp

### ISSUE THREAD

**Issue by qwer130140190** [xianyunleo/EServer#121]
希望能支持一下
<img width="577" alt="image" src="https://github.com/xianyunleo/EServer/assets/29937512/30c90b69-2297-44e3-86de-1a493a59b970">

**Comment by xianyunleo** [comment]
EServer的版本，系统说一下

**Comment by qwer130140190** [comment]
> EServer的版本，系统说一下

版本3.2.1，系统是macos 14.3 (23D56)

**Comment by xianyunleo** [comment]
重新安装php再试。EServer V3.0.2 起，mac，gd扩展支持webp，从php7.0开始。

**Comment by qwer130140190** [comment]
> 重新安装php再试。EServer V3.0.2 起，mac，gd扩展支持webp，从php7.0开始。

重新安装后可以了
