### ISSUE TITLE
启用环境变量出现错误

### ISSUE THREAD

**Issue by gzxy-0102** [xianyunleo/EServer#122]
![image](https://github.com/user-attachments/assets/f598a64f-75ed-412c-ba43-1b5bf3e5ccc6)

**Comment by xianyunleo** [comment]
环境变量-》用户变量-》Path 的值截图给我看一下

**Comment by gzxy-0102** [comment]
> 系统的环境变量-》用户变量-》Path 的值截图给我看一下 @gzxy-0102

![image](https://github.com/user-attachments/assets/f74c5056-412f-4a07-b40e-452e8a72c1e6)

**Comment by xianyunleo** [comment]
@gzxy-0102 点编辑文本，然后将全部的发出来

**Comment by gzxy-0102** [comment]
D:\sdk\miniconda3;D:\sdk\miniconda3\Library\mingw-w64\bin;D:\sdk\miniconda3\Library\usr\bin;D:\sdk\miniconda3\Library\bin;D:\sdk\miniconda3\Scripts;C:\Users\gzxy_\AppData\Local\Microsoft\WindowsApps;C:\Users\gzxy_\go\bin;C:\Users\gzxy_\AppData\Local\JetBrains\Toolbox\scripts;D:\Program Files\Microsoft VS Code\bin;C:\Users\gzxy_\AppData\Roaming\npm;c:\users\gzxy_\.local\bin;D:\sdk\ffmpeg\bin;D:\Program Files\Multipass\bin;%USERPROFILE%\go\bin

**Comment by gzxy-0102** [comment]
![image](https://github.com/user-attachments/assets/a7c90fe4-fff3-4bd2-b724-0eb7c68f8d0f)

**Comment by xianyunleo** [comment]
加微信或者QQ群协助解决吧

**Comment by gzxy-0102** [comment]
> 加微信或者QQ群协助解决吧 @gzxy-0102

微信 gzxy-0102
