### ISSUE TITLE
mac mini m4下，打不开，提示：“EServer”已损坏，无法打开。 你应该将它移到废纸篓。

### ISSUE THREAD

**Issue by SimonSUSU** [xianyunleo/EServer#133]
“EServer”已损坏，无法打开。 你应该将它移到废纸篓。
![WX20241213-164414@2x](https://github.com/user-attachments/assets/36c3a2a1-9ef0-4e07-9673-1c90de395594)

**Comment by xianyunleo** [comment]
看文档哈
