### ISSUE TITLE
php8.2安装memcache扩展报错

### ISSUE THREAD

**Issue by qwer130140190** [xianyunleo/EServer#85]
![20231022140356](https://github.com/xianyunleo/EasySrv/assets/29937512/d3ba1372-55c8-43cb-bbc2-af4baaa435e6)
macos版本13.5.1 (22G90)
easysrv版本1.7.1 (1.7.1)

**Comment by qwer130140190** [comment]
已解决brew install zlib
脚本修改为
./configure --with-php-config=$phpDir/bin/php-config --with-zlib-dir=/opt/homebrew/Cellar/zlib/1.3

**Comment by xianyunleo** [comment]
收到，下个版本修复

**Comment by xianyunleo** [comment]
新版2.0已修复
