### ISSUE TITLE
安装mysql5.7 出错

### ISSUE THREAD

**Issue by liuyami** [xianyunleo/EServer#91]
配置过程中发生错误，Command failed: D:\dev\EServer\core\software\server\mysql-5.7\bin\mysqld.exe --defaults-file=D:\dev\EServer\core\software\server\mysql-5.7\my.ini --initialize

之前安装过5.7，后来卸载了，因为一个项目要用到5.7，又准备装上，于是这样了，彻底删掉 eserver，重新下载，安装还是这样，是不是之前那次的原因？

windows 10 22H2

**Comment by xianyunleo** [comment]
`D:\dev\EServer\core\software\server\mysql-5.7\bin\mysqld.exe --defaults-file=D:\dev\EServer\core\software\server\mysql-5.7\my.ini --initialize`

你打开cmd终端执行这个命令，看报错提示和MySQL日志。
