### ISSUE TITLE
MAC系统安装新的EServer（2.9）有问题

### ISSUE THREAD

**Issue by ghostrin** [xianyunleo/EServer#93]
MAC系统下已安装EasySrv（1.7），再安装新的EServer（2.9），实际并不能覆盖安装，还是存在两个。
当运行安装新的EServer（2.9），原来的旧的数据库mysql5.7数据也不能自动替换过来。

请问如何在新安装的EServer（2.9）下先把旧版数据库（同为mysql5.7）迁移过来？旧版的EasySrv（1.7）运行程序已将删除，数据库还在

**Comment by xianyunleo** [comment]
https://github.com/xianyunleo/EServer/issues/94
